django/homesite/chat/urls.py
# chat/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("", views.index, name="index"),
    path("<str:room_name>/", views.room, name="room"),
    path("test", views.test, name="test"),
    path("readings", views.readings, name="readings"),
]

django/homesite/homesite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("polls/", include("polls.urls")),
    path("chat/", include("chat.urls")),
    path("sensors/", include("sensors.urls")),
]

django/homesite/polls/urls.py
from django.urls import path
from . import views

# namespacess the polls urls
app_name = "polls"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:question_id>/", views.detail, name="detail"),
    path("<int:question_id>/results/", views.results, name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

django/homesite/sensors/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:reading_id>/", views.detail, name="detail"),
]

django/homesite/chat/models.py
from django.db import models

# Create your models here.

django/homesite/polls/models.py
import datetime
from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def __str__(self):
        return self.question_text
    
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

django/homesite/sensors/models.py
from django.db import models



class SensorReading(models.Model):

    param = models.CharField(max_length=10, default='unk')
    date = models.DateTimeField("datetime")
    reading = models.FloatField("reading")

    def __str__(self):
        return f'{self.date} : {self.param} : {self.reading}'
    

django/homesite/chat/views.py
# chat/views.py
from django.shortcuts import render
from sensors.models import SensorReading


def index(request):
    return render(request, "chat/index.html")

def room(request, room_name):
    return render(request, "chat/room.html", {"room_name": room_name})

def test(request):
    return render(request, "chat/test.html")

def readings(request):
    latest_readings_list = SensorReading.objects.latest("datetime")[:5]
    context = {"latest_question_list": latest_readings_list}
    return render(request, "chat/readings.html", context)

django/homesite/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
from django.template import loader
from .models import Question





def index(request):
    latest_question_list = Question.objects.order_by("-pub_date")[:5]
    context = {"latest_question_list": latest_question_list}
    return render(request, "polls/index.html", context)

# def detail(request, question_id):
#     try:
#         question = Question.objects.get(pk=question_id)
#     except Question.DoesNotExist:
#         raise Http404("Question does not exist")
#     return render(request, "polls/detail.html", {"question": question})

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/detail.html", {"question": question})

# def detail(request, question_id):
#     return HttpResponse("You're looking at question %s." % question_id)


def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)


def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)


# most basic view
# def index(request):
#     return HttpResponse("Hello, world. You're at the polls index.")


# def index(request):
#     latest_question_list = Question.objects.order_by("-pub_date")[:5]
#     output = ", ".join([q.question_text for q in latest_question_list])
#     return HttpResponse(output)


# def index(request):
#     latest_question_list = Question.objects.order_by("-pub_date")[:5]
#     template = loader.get_template("polls/index.html")
#     context = {
#         "latest_question_list": latest_question_list,
#     }
#     return HttpResponse(template.render(context, request))

django/homesite/sensors/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
from django.template import loader
from .models import SensorReading



def index(request):
    return HttpResponse("Hello, world. You're at the polls index.")

def detail(request, reading_id):
    reading = get_object_or_404(SensorReading, pk=reading_id)
    return render(request, "sensors/detail.html", {"reading": reading})

django/homesite/chat/templates/chat/index.html
<!-- chat/templates/chat/index.html -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Rooms</title>
</head>
<body>
    What chat room would you like to enter?<br>
    <input id="room-name-input" type="text" size="100"><br>
    <input id="room-name-submit" type="button" value="Enter">

    <script>
        document.querySelector('#room-name-input').focus();
        document.querySelector('#room-name-input').onkeyup = function(e) {
            if (e.key === 'Enter') {  // enter, return
                document.querySelector('#room-name-submit').click();
            }
        };

        document.querySelector('#room-name-submit').onclick = function(e) {
            var roomName = document.querySelector('#room-name-input').value;
            window.location.pathname = '/chat/' + roomName + '/';
        };
    </script>
</body>
</html>

django/homesite/chat/templates/chat/readings.html
<!-- chat/templates/chat/room.html -->
{% load static %}
<link rel="stylesheet" href="{% static 'chat/style.css' %}">


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Room</title>
</head>
<body>
    Welcome to the readings page.
    <script async src="{% static 'chat/test.js' %}"></script>
</body>
</html>

django/homesite/chat/templates/chat/room.html
<!-- chat/templates/chat/room.html -->
{% load static %}
<link rel="stylesheet" href="{% static 'chat/style.css' %}">


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Room</title>
</head>
<body>
    <textarea id="chat-log" class="textbox" cols="100" rows="20"></textarea><br>
    <input id="chat-message-input" type="text" size="100"><br>
    <input id="chat-message-submit" type="button" value="Send"><br>
    <button id="button_1" class="bType_1">Cool Button</button>
    {{ room_name|json_script:"room-name" }}
    <script async src="{% static 'chat/room.js' %}"></script>
</body>
</html>

django/homesite/chat/templates/chat/test.html
<!-- chat/templates/chat/room.html -->
{% load static %}
<link rel="stylesheet" href="{% static 'chat/style.css' %}">


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Room</title>
</head>
<body>
    Welcome to the test page.
    <script async src="{% static 'chat/test.js' %}"></script>
</body>
</html>

django/homesite/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul>

django/homesite/polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <!-- <li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li> -->
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

django/homesite/sensors/templates/sensors/detail.html
<h1>{{ reading.param }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul>